name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: brew install hello
    - name: Run a multi-line script
      run: hello
